// <auto-generated />
using System;
using GermanVerbTester.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GermanVerbTester.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251126152436_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GermanVerbTester.Models.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("GermanVerbTester.Models.Verb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("English")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("German")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Verbs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            English = "to be",
                            German = "sein"
                        },
                        new
                        {
                            Id = 2,
                            English = "to have",
                            German = "haben"
                        },
                        new
                        {
                            Id = 3,
                            English = "to become",
                            German = "werden"
                        },
                        new
                        {
                            Id = 4,
                            English = "to be able to",
                            German = "können"
                        },
                        new
                        {
                            Id = 5,
                            English = "to have to",
                            German = "müssen"
                        },
                        new
                        {
                            Id = 6,
                            English = "to say",
                            German = "sagen"
                        },
                        new
                        {
                            Id = 7,
                            English = "to do",
                            German = "machen"
                        },
                        new
                        {
                            Id = 8,
                            English = "to give",
                            German = "geben"
                        },
                        new
                        {
                            Id = 9,
                            English = "to come",
                            German = "kommen"
                        },
                        new
                        {
                            Id = 10,
                            English = "should",
                            German = "sollen"
                        },
                        new
                        {
                            Id = 11,
                            English = "to want",
                            German = "wollen"
                        },
                        new
                        {
                            Id = 12,
                            English = "to go",
                            German = "gehen"
                        },
                        new
                        {
                            Id = 13,
                            English = "to know",
                            German = "wissen"
                        },
                        new
                        {
                            Id = 14,
                            English = "to see",
                            German = "sehen"
                        },
                        new
                        {
                            Id = 15,
                            English = "to let",
                            German = "lassen"
                        },
                        new
                        {
                            Id = 16,
                            English = "to stand",
                            German = "stehen"
                        },
                        new
                        {
                            Id = 17,
                            English = "to find",
                            German = "finden"
                        },
                        new
                        {
                            Id = 18,
                            English = "to stay",
                            German = "bleiben"
                        },
                        new
                        {
                            Id = 19,
                            English = "to lie",
                            German = "liegen"
                        },
                        new
                        {
                            Id = 20,
                            English = "to be called",
                            German = "heißen"
                        },
                        new
                        {
                            Id = 21,
                            English = "to think",
                            German = "denken"
                        },
                        new
                        {
                            Id = 22,
                            English = "to take",
                            German = "nehmen"
                        },
                        new
                        {
                            Id = 23,
                            English = "to do",
                            German = "tun"
                        },
                        new
                        {
                            Id = 24,
                            English = "to be allowed to",
                            German = "dürfen"
                        },
                        new
                        {
                            Id = 25,
                            English = "to believe",
                            German = "glauben"
                        },
                        new
                        {
                            Id = 26,
                            English = "to hold",
                            German = "halten"
                        },
                        new
                        {
                            Id = 27,
                            English = "to name",
                            German = "nennen"
                        },
                        new
                        {
                            Id = 28,
                            English = "to like",
                            German = "mögen"
                        },
                        new
                        {
                            Id = 29,
                            English = "to show",
                            German = "zeigen"
                        },
                        new
                        {
                            Id = 30,
                            English = "to lead",
                            German = "führen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
